"""add_user_addresses_relationship

Revision ID: 10c84f91592b
Revises: 0cdd7ea9fd7c
Create Date: 2025-08-07 14:35:35.318662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c84f91592b'
down_revision: Union[str, None] = '0cdd7ea9fd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
