# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x11\x43reateUserRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"\x1f\n\rMobileRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"+\n\rAvatarRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\t\"/\n\x0fUsernameRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\"/\n\x0fPasswordRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08password\x18\x02 \x01(\t\")\n\x0bPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r\"4\n\x10VerfyUserRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x81\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06mobile\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x10\n\x08is_staff\x18\x06 \x01(\x08\x12\x12\n\nlast_login\x18\x07 \x01(\t\"+\n\x10UserInfoResponse\x12\x17\n\x04user\x18\x01 \x01(\x0b\x32\t.UserInfo\",\n\x10UserListResponse\x12\x18\n\x05users\x18\x01 \x03(\x0b\x32\t.UserInfo2\xf5\x03\n\x04User\x12\x33\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x11.UserInfoResponse\x12,\n\x0bGetUserById\x12\n.IdRequest\x1a\x11.UserInfoResponse\x12\x34\n\x0fGetUserByMobile\x12\x0e.MobileRequest\x1a\x11.UserInfoResponse\x12:\n\x10UpdateUserAvatar\x12\x0e.AvatarRequest\x1a\x16.google.protobuf.Empty\x12:\n\x0eUpdateUsername\x12\x10.UsernameRequest\x1a\x16.google.protobuf.Empty\x12:\n\x0eUpdatePassword\x12\x10.PasswordRequest\x1a\x16.google.protobuf.Empty\x12.\n\x0bGetUserList\x12\x0c.PageRequest\x1a\x11.UserListResponse\x12\x32\n\nVerifyUser\x12\x11.VerfyUserRequest\x1a\x11.UserInfoResponse\x12<\n\x17GetOrCreateUserByMobile\x12\x0e.MobileRequest\x1a\x11.UserInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=43
  _globals['_CREATEUSERREQUEST']._serialized_end=78
  _globals['_IDREQUEST']._serialized_start=80
  _globals['_IDREQUEST']._serialized_end=103
  _globals['_MOBILEREQUEST']._serialized_start=105
  _globals['_MOBILEREQUEST']._serialized_end=136
  _globals['_AVATARREQUEST']._serialized_start=138
  _globals['_AVATARREQUEST']._serialized_end=181
  _globals['_USERNAMEREQUEST']._serialized_start=183
  _globals['_USERNAMEREQUEST']._serialized_end=230
  _globals['_PASSWORDREQUEST']._serialized_start=232
  _globals['_PASSWORDREQUEST']._serialized_end=279
  _globals['_PAGEREQUEST']._serialized_start=281
  _globals['_PAGEREQUEST']._serialized_end=322
  _globals['_VERFYUSERREQUEST']._serialized_start=324
  _globals['_VERFYUSERREQUEST']._serialized_end=376
  _globals['_USERINFO']._serialized_start=379
  _globals['_USERINFO']._serialized_end=508
  _globals['_USERINFORESPONSE']._serialized_start=510
  _globals['_USERINFORESPONSE']._serialized_end=553
  _globals['_USERLISTRESPONSE']._serialized_start=555
  _globals['_USERLISTRESPONSE']._serialized_end=599
  _globals['_USER']._serialized_start=602
  _globals['_USER']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
